services:
  postgres_keycloak:
    image: postgres:16.2
    container_name: keycloak_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs/.local/.keycloak
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak_service
    command: start
    env_file:
      - .envs/.local/.keycloak
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres_keycloak
    networks:
      - keycloak_network

volumes:
  postgres_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge