volumes:
  valami_local_postgres_data: {}
  valami_local_pg_admin_data: {}
  valami_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: valami_local_django
    container_name: valami_local_django
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    image: postgres:16
    container_name: valami_local_postgres
    volumes:
      - valami_local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 3s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin_valami
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - valami_local_pg_admin_data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: my_awesome_project_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:6
    container_name: valami_local_redis

    volumes:
      - valami_local_redis_data:/data

  celeryworker:
    <<: *django
    image: valami_local_celeryworker
    container_name: valami_local_celeryworker
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: valami_local_celerybeat
    container_name: valami_local_celerybeat
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: valami_local_flower
    container_name: valami_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
